import React, { useState } from 'react';
import {
  ExternalLink,
  Copy,
  Check,
  Sparkles,
  Info,
  ArrowRight,
  BookOpen,
  UploadCloud,
  FileText,
} from 'lucide-react';
import { Button } from '@/src/components/ui/button';
import { Textarea } from '@/src/components/ui/textarea';
import { toast } from '@/src/components/ui/toast';

interface NotebookLMBindingProps {
  onImport: (text: string) => void;
  isLoading?: boolean;
}

export function NotebookLMBridge({ onImport, isLoading }: NotebookLMBindingProps) {
  const [copiedStep, setCopiedStep] = useState(false);
  const [notebookLmOutput, setNotebookLmOutput] = useState('');

  const launchNotebookLM = () => {
    window.open('https://notebooklm.google.com/', '_blank', 'noopener,noreferrer');
  };

  const handleImport = () => {
    if (!notebookLmOutput.trim()) {
      toast.error('Please paste the summary, study guide, or notes generated by NotebookLM first.');
      return;
    }
    onImport(notebookLmOutput.trim());
  };

  return (
    <div className="rounded-xl border border-sky-200/60 dark:border-sky-800/40 bg-gradient-to-b from-sky-50/50 to-white dark:from-sky-950/20 dark:to-card p-5 space-y-4">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 pb-3 border-b border-sky-100 dark:border-sky-900/40">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-sky-600/10 dark:bg-sky-400/10 flex items-center justify-center text-sky-600 dark:text-sky-400 font-semibold">
            <BookOpen className="w-4 h-4" />
          </div>
          <div>
            <h4 className="text-sm font-semibold text-foreground flex items-center gap-1.5">
              Google NotebookLM Companion
              <span className="text-[10px] font-medium px-2 py-0.5 rounded-full bg-emerald-100 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300">
                100% Free
              </span>
            </h4>
            <p className="text-xs text-muted-foreground">
              Direct guided bridge: Log into your Google account, upload audio as a source, and sync into Minute.
            </p>
          </div>
        </div>

        <Button
          type="button"
          onClick={launchNotebookLM}
          className="bg-sky-600 hover:bg-sky-700 text-white text-xs h-8 px-3 rounded-lg shadow-sm gap-1.5 shrink-0"
        >
          <ExternalLink className="w-3.5 h-3.5" />
          Launch NotebookLM
        </Button>
      </div>

      {/* Workflow Step Badges */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-2.5 text-xs">
        <div className="p-2.5 rounded-lg bg-white/80 dark:bg-card/80 border border-sky-100 dark:border-sky-900/30 flex items-start gap-2">
          <span className="w-5 h-5 rounded-full bg-sky-100 dark:bg-sky-900 text-sky-700 dark:text-sky-300 flex items-center justify-center text-[10px] font-bold shrink-0 mt-0.5">
            1
          </span>
          <p className="text-muted-foreground">
            Click <strong>Launch NotebookLM</strong>, sign into your Google account and click <strong>Create new notebook</strong>.
          </p>
        </div>

        <div className="p-2.5 rounded-lg bg-white/80 dark:bg-card/80 border border-sky-100 dark:border-sky-900/30 flex items-start gap-2">
          <span className="w-5 h-5 rounded-full bg-sky-100 dark:bg-sky-900 text-sky-700 dark:text-sky-300 flex items-center justify-center text-[10px] font-bold shrink-0 mt-0.5">
            2
          </span>
          <p className="text-muted-foreground">
            In NotebookLM, click <strong>Upload Source</strong> and select your meeting audio or transcript file.
          </p>
        </div>

        <div className="p-2.5 rounded-lg bg-white/80 dark:bg-card/80 border border-sky-100 dark:border-sky-900/30 flex items-start gap-2">
          <span className="w-5 h-5 rounded-full bg-sky-100 dark:bg-sky-900 text-sky-700 dark:text-sky-300 flex items-center justify-center text-[10px] font-bold shrink-0 mt-0.5">
            3
          </span>
          <p className="text-muted-foreground">
            Copy the notes/transcript from NotebookLM and paste below to standardize into Company Minutes.
          </p>
        </div>
      </div>

      <div className="space-y-1.5 pt-1">
        <label className="text-xs font-medium text-foreground flex items-center justify-between">
          <span>Paste NotebookLM Output / Source Content:</span>
          {notebookLmOutput && (
            <span className="text-[11px] text-muted-foreground">
              {notebookLmOutput.length.toLocaleString()} characters
            </span>
          )}
        </label>
        <Textarea
          value={notebookLmOutput}
          onChange={(e) => setNotebookLmOutput(e.target.value)}
          placeholder="Paste meeting text, notes, or NotebookLM summary here..."
          className="min-h-[140px] text-xs font-mono leading-relaxed bg-white/90 dark:bg-card/90"
        />
      </div>

      <div className="flex items-center justify-between pt-1">
        <p className="text-[11px] text-muted-foreground flex items-center gap-1">
          <Info className="w-3.5 h-3.5 text-sky-500" />
          The standard corporate minute engine will structure topics, decisions, and tasks.
        </p>

        <Button
          type="button"
          onClick={handleImport}
          disabled={!notebookLmOutput.trim() || isLoading}
          className="bg-emerald-600 hover:bg-emerald-700 text-white text-xs h-8 px-4 rounded-lg shadow-sm gap-1.5"
        >
          <Sparkles className="w-3.5 h-3.5" />
          {isLoading ? 'Processing Minutes...' : 'Synthesize Company Minute'}
        </Button>
      </div>
    </div>
  );
}
