import { useState, useEffect, useMemo, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  format, parseISO, isPast, isToday, isTomorrow, differenceInHours,
  startOfMonth, endOfMonth, startOfWeek, endOfWeek, eachDayOfInterval,
  isSameMonth, isSameDay, addMonths, subMonths, getHours
} from 'date-fns';
import {
  Bell, Plus, Trash2, Edit3, Clock, Mail, Users, X, Check,
  AlertCircle, RefreshCw, ToggleLeft, ToggleRight,
  Calendar, CheckCircle2, Link2, ChevronDown, Eye, BellOff,
  Zap, Search, LayoutList, ChevronLeft, ChevronRight, ShieldAlert,
} from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '@/src/hooks/useAuth';
import { useAppData } from '@/src/contexts/AppDataContext';
import { useWorkspace } from '@/src/hooks/use-workspace';
import { useSearchParams } from 'react-router-dom';
import { useSetPageTitle } from '@/src/contexts/PageContext';
import { Button } from '@/src/components/ui/button';
import { Input } from '@/src/components/ui/input';
import { Tabs, TabsList, TabsTrigger } from '@/src/components/ui/tabs';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/src/components/ui/dropdown-menu";
import type { Reminder, ReminderFrequency } from '@/src/types/tasks';
import { supabase } from '@/src/integrations/supabase/client';

/**
 * Titles used by the system when auto-creating reminders (now deprecated).
 * These are NOT user-created reminders and should be excluded from the list.
 */
const SYSTEM_REMINDER_TITLES = [
  'New Task Created',
  'Task Reminder',
] as const;

/** Returns true if a reminder was auto-generated by the system (not the user). */
function isSystemReminder(r: Reminder): boolean {
  return (
    SYSTEM_REMINDER_TITLES.includes(r.title as any) ||
    r.title?.startsWith('Mentioned') ||
    r.title?.startsWith('Update on Assigned Task:')
  );
}

/* ─── Constants ─────────────────────────────────────────────────────────────── */
const FREQ_LABELS: Record<ReminderFrequency, string> = {
  once: 'Once', hourly: 'Hourly', every_6_hours: 'Every 6h',
  daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly',
};

const FREQ_COLORS: Record<ReminderFrequency, string> = {
  once:         'bg-slate-100 text-slate-600 border-slate-200',
  hourly:       'bg-blue-50 text-blue-600 border-blue-200',
  every_6_hours:'bg-indigo-50 text-indigo-600 border-indigo-200',
  daily:        'bg-indigo-50 text-indigo-600 border-indigo-200',
  weekly:       'bg-purple-50 text-purple-600 border-purple-200',
  monthly:      'bg-pink-50 text-pink-600 border-pink-200',
};

interface ReminderFormData {
  title: string; body: string; remindAt: string; endAt: string;
  frequency: ReminderFrequency; recipientIds: string[];
  sendEmail: boolean; mainTaskId: string;
}
const emptyForm = (): ReminderFormData => ({
  title: '', body: '', remindAt: '', endAt: '', frequency: 'once',
  recipientIds: [], sendEmail: false, mainTaskId: '',
});

/* ─── Helpers ───────────────────────────────────────────────────────────────── */
function getRelativeTime(dateStr: string): { label: string; tone: 'ok' | 'soon' | 'overdue' | 'today' } {
  try {
    const d = parseISO(dateStr);
    if (isToday(d)) return { label: `Today at ${format(d, 'h:mm a')}`, tone: 'today' };
    if (isTomorrow(d)) return { label: `Tomorrow at ${format(d, 'h:mm a')}`, tone: 'soon' };
    if (isPast(d)) return { label: `Overdue · ${format(d, 'MMM d, h:mm a')}`, tone: 'overdue' };
    const hrs = differenceInHours(d, new Date());
    if (hrs < 48) return { label: `In ${hrs}h · ${format(d, 'h:mm a')}`, tone: 'soon' };
    return { label: format(d, 'EEE, MMM d · h:mm a'), tone: 'ok' };
  } catch {
    return { label: 'Unknown date', tone: 'ok' };
  }
}

const toneStyles = {
  ok:      'text-muted-foreground',
  soon:    'text-amber-600 dark:text-amber-400 font-semibold',
  overdue: 'text-red-600 dark:text-red-400 font-bold',
  today:   'text-indigo-600 dark:text-indigo-400 font-semibold',
};
const toneIconStyles = {
  ok:      'text-muted-foreground',
  soon:    'text-amber-500',
  overdue: 'text-red-500',
  today:   'text-indigo-500',
};

/* ─── Main Component ────────────────────────────────────────────────────────── */
export function TaskReminders() {
  const { user: currentUser } = useAuth();
  const { reminders: allReminders, addReminder, updateReminder, deleteReminder, toggleReminderActive, users } = useAppData();
  const { wsMembers: activeUsers, wsTasks: allMainTasks } = useWorkspace();

  const appUser = users.find(u => u.id === currentUser?.id);
  const isExternalHr = appUser?.privileges?.tasks?.isExternalHr;

  const mainTasks = useMemo(() => {
    if (isExternalHr) return allMainTasks.filter(m => !!m.is_hr_task);
    return allMainTasks;
  }, [allMainTasks, isExternalHr]);

  const reminders = useMemo(() => {
    if (isExternalHr) {
      const hrTaskIds = new Set(mainTasks.map(m => m.id));
      return allReminders.filter(r => r.mainTaskId && hrTaskIds.has(r.mainTaskId));
    }
    return allReminders;
  }, [allReminders, mainTasks, isExternalHr]);
  const [searchParams, setSearchParams] = useSearchParams();

  /* ── One-time cleanup: remove all system-generated reminders from DB ─── */
  useEffect(() => {
    // Silently purge system reminders (e.g. 'New Task Created', 'Mentioned...')
    // that were inserted by the now-removed auto-reminder logic.
    const systemIds = reminders
      .filter(isSystemReminder)
      .map(r => r.id);

    if (systemIds.length === 0) return;

    supabase
      .from('reminders')
      .delete()
      .in('id', systemIds)
      .then(({ error }) => {
        if (error) console.error('Auto-cleanup of system reminders failed:', error);
      });
  // Run once — only when reminders first load
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [reminders.length > 0]);

  /* ── Manual purge handler (admin) ───────────────────────────────────── */
  const [purging, setPurging] = useState(false);
  const handlePurgeSystemReminders = useCallback(async () => {
    setPurging(true);
    try {
      const { error } = await supabase
        .from('reminders')
        .delete()
        .or(
          `title.eq.New Task Created,title.ilike.Mentioned%,title.eq.Task Reminder,title.ilike.Update on Assigned Task:%`
        );
      if (error) throw error;
      toast.success('System reminders cleared successfully');
    } catch (err) {
      console.error('Purge failed:', err);
      toast.error('Failed to clear system reminders');
    } finally {
      setPurging(false);
    }
  }, []);

  /* Form state */
  const [showForm, setShowForm]     = useState(false);
  const [editingId, setEditingId]   = useState<string | null>(null);
  const [form, setForm]             = useState<ReminderFormData>(emptyForm());
  const [formError, setFormError]   = useState('');
  const [recipientOpen, setRecipientOpen] = useState(false);

  /* List / filter state */
  const [search, setSearch]         = useState('');
  const [filterStatus, setFilterStatus] = useState<'all' | 'active' | 'inactive'>('all');
  const [tab, setTab]               = useState<'all' | 'mine' | 'shared'>('all');
  const [selected, setSelected]     = useState<Reminder | null>(null);

  /* Calendar state */
  const [viewMode, setViewMode]     = useState<'calendar' | 'list'>('calendar');
  const [currentDate, setCurrentDate] = useState(new Date());
  const [selectedDate, setSelectedDate] = useState<Date>(new Date());

  /* Derived lists */
  const myReminders = useMemo(() => 
    reminders.filter(r => r.createdBy === currentUser?.id),
    [reminders, currentUser?.id]
  );

  const sharedWithMe = useMemo(() => 
    reminders.filter(r => 
      (r.recipientIds?.length === 0 || r.recipientIds?.includes(currentUser?.id || '')) && 
      r.createdBy !== currentUser?.id
    ),
    [reminders, currentUser?.id]
  );

  const pool = useMemo(() => {
    if (tab === 'mine') return myReminders;
    if (tab === 'shared') return sharedWithMe;
    // 'all' shows everything in the database
    return reminders;
  }, [tab, myReminders, sharedWithMe, reminders]);

  const filtered = useMemo(() => {
    return pool
      .filter(r => filterStatus === 'all' ? true : filterStatus === 'active' ? r.isActive : !r.isActive)
      .filter(r => !search.trim() || r.title.toLowerCase().includes(search.toLowerCase()))
      .sort((a, b) => new Date(a.remindAt).getTime() - new Date(b.remindAt).getTime());
  }, [pool, filterStatus, search]);

  const activeCount = useMemo(() => 
    pool.filter(r => r.isActive).length,
    [pool]
  );

  const overdueCount = useMemo(() => 
    pool.filter(r => r.isActive && isPast(parseISO(r.remindAt)) && !isToday(parseISO(r.remindAt))).length,
    [pool]
  );

  // Pre-group reminders for calendar (optimization)
  const remindersDayMap = useMemo(() => {
    const map: Record<string, Reminder[]> = {};
    filtered.forEach(r => {
      const dateKey = format(parseISO(r.remindAt), 'yyyy-MM-dd');
      if (!map[dateKey]) map[dateKey] = [];
      map[dateKey].push(r);
    });
    return map;
  }, [filtered]);

  /* Form helpers */
  const openCreate = () => { setForm(emptyForm()); setEditingId(null); setFormError(''); setShowForm(true); };
  const openEdit = (rem: Reminder) => {
    setForm({
      title: rem.title, body: rem.body, remindAt: rem.remindAt.slice(0, 16),
      endAt: rem.endAt ? rem.endAt.slice(0, 16) : '', frequency: rem.frequency,
      recipientIds: [...rem.recipientIds], sendEmail: rem.sendEmail, mainTaskId: rem.mainTaskId ?? '',
    });
    setEditingId(rem.id);
    setFormError('');
    setShowForm(true);
    setSelected(null);
  };

  useSetPageTitle(
    'Task Reminders',
    `${activeCount} active${overdueCount > 0 ? ` · ${overdueCount} overdue` : ''} · ${pool.length} total reminders tracked`,
    <div className="flex items-center gap-3">
      {/* View Mode Toggle */}
      <div className="flex items-center gap-1 bg-slate-100 p-1 rounded-lg border border-slate-200">
        <Button 
          variant={viewMode === 'calendar' ? 'secondary' : 'ghost'} 
          size="sm" 
          onClick={() => setViewMode('calendar')}
          className={`h-8 px-3 gap-2 font-bold text-[10px] uppercase tracking-tight ${viewMode === 'calendar' ? 'bg-white shadow-sm text-indigo-600' : 'text-slate-500'}`}
        >
          <Calendar className="w-3.5 h-3.5" /> Calendar
        </Button>
        <Button 
          variant={viewMode === 'list' ? 'secondary' : 'ghost'} 
          size="sm" 
          onClick={() => setViewMode('list')}
          className={`h-8 px-3 gap-2 font-bold text-[10px] uppercase tracking-tight ${viewMode === 'list' ? 'bg-white shadow-sm text-indigo-600' : 'text-slate-500'}`}
        >
          <LayoutList className="w-3.5 h-3.5" /> List
        </Button>
      </div>

      <div className="h-8 w-[1px] bg-slate-200 mx-1 hidden sm:block" />

      {/* Tab Filter */}
      <TabsList className="h-9 bg-slate-100 border border-slate-200 p-0.5 hidden md:flex">
        <TabsTrigger active={tab === 'all'} onClick={() => setTab('all')} className="h-8 px-3 text-[10px] font-bold uppercase tracking-tight">All</TabsTrigger>
        <TabsTrigger active={tab === 'mine'} onClick={() => setTab('mine')} className="h-8 px-3 text-[10px] font-bold uppercase tracking-tight">Mine</TabsTrigger>
        <TabsTrigger active={tab === 'shared'} onClick={() => setTab('shared')} className="h-8 px-3 text-[10px] font-bold uppercase tracking-tight">Shared</TabsTrigger>
      </TabsList>

      <div className="h-8 w-[1px] bg-slate-200 mx-1 hidden sm:block" />

      <Button 
        size="sm" 
        onClick={openCreate}
        className="h-9 px-4 gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-[11px] uppercase tracking-tight shadow-md transition-all active:scale-95"
      >
        <Plus className="w-4 h-4" /> <span className="hidden sm:inline">New Reminder</span>
      </Button>
    </div>,
    [viewMode, tab, activeCount, overdueCount, pool.length]
  );

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault(); setFormError('');
    if (!form.title.trim()) { setFormError('Title is required.'); return; }
    if (!form.remindAt)     { setFormError('Please set a date/time.'); return; }
    if (form.recipientIds.length === 0) { setFormError('Select at least one recipient.'); return; }
    const payload = {
      title: form.title.trim(), body: form.body.trim(),
      remindAt: new Date(form.remindAt).toISOString(),
      endAt: form.endAt ? new Date(form.endAt).toISOString() : null,
      frequency: form.frequency, recipientIds: form.recipientIds,
      sendEmail: form.sendEmail, mainTaskId: form.mainTaskId || null,
    };
    if (editingId) updateReminder(editingId, { ...payload, isActive: true });
    else addReminder({ ...payload, isActive: true, createdBy: currentUser!.id });
    setShowForm(false); setEditingId(null);
  };

  const toggleRecipient = (id: string) =>
    setForm(p => ({ ...p, recipientIds: p.recipientIds.includes(id) ? p.recipientIds.filter(x => x !== id) : [...p.recipientIds, id] }));

  const TimeBlock = ({ title, reminders }: { title: string, reminders: Reminder[] }) => {
    if (reminders.length === 0) return null;
    return (
      <div className="space-y-3">
        <div className="flex items-center gap-2">
          <h4 className="text-xs font-bold uppercase tracking-wider text-muted-foreground">{title}</h4>
          <div className="h-px bg-border flex-1"></div>
        </div>
        <div className="space-y-2">
          {reminders.map(rem => {
            const isAdminCal = (currentUser as any)?.privileges?.users?.canManage || (currentUser as any)?.role === 'admin' || (currentUser as any)?.role === 'co-admin';
            const isOwnerCal = rem.createdBy === currentUser?.id;
            const canEditCal = isOwnerCal || isAdminCal;
            return (
              <div key={rem.id} className={`p-2.5 rounded-xl border transition-all group ${rem.isActive ? 'bg-card border-border hover:border-indigo-200 hover:shadow-sm' : 'bg-muted/30 border-border/50 opacity-70'}`}>
                <div className="flex items-start justify-between gap-2">
                  <div className="flex items-center gap-1.5 min-w-0">
                    <div className={`w-1.5 h-1.5 rounded-full ${rem.isActive ? 'bg-indigo-500' : 'bg-muted-foreground'}`} />
                    <span className="text-xs font-semibold text-foreground truncate">{format(parseISO(rem.remindAt), 'h:mm a')}</span>
                  </div>
                  {canEditCal && (
                    <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                      <button onClick={() => openEdit(rem)} title={isAdminCal && !isOwnerCal ? 'Edit (Admin Override)' : 'Edit'} className="p-1 hover:bg-muted rounded text-muted-foreground"><Edit3 className="w-3.5 h-3.5" /></button>
                      <button onClick={() => deleteReminder(rem.id)} title={isAdminCal && !isOwnerCal ? 'Delete (Admin Override)' : 'Delete'} className="p-1 hover:bg-red-50 rounded text-red-500"><Trash2 className="w-3.5 h-3.5" /></button>
                    </div>
                  )}
                </div>
                <p className="text-xs font-medium text-foreground mt-1.5 line-clamp-2 leading-tight">{rem.title}</p>
                {rem.body && <p className="text-[10px] text-muted-foreground mt-1 line-clamp-1">{rem.body}</p>}
                {isOwnerCal ? (
                  <span className="mt-1.5 inline-flex items-center gap-1 text-[9px] font-bold text-indigo-600 bg-indigo-50 border border-indigo-100 px-1.5 py-0.5 rounded-full">✦ You</span>
                ) : (
                  <span className="mt-1.5 inline-flex items-center gap-1 text-[9px] font-medium text-slate-400 bg-slate-50 border border-slate-100 px-1.5 py-0.5 rounded-full">
                    {users.find(u => u.id === rem.createdBy)?.name?.split(' ')[0] ?? 'System'}
                  </span>
                )}
              </div>
            );
          })}
        </div>
      </div>
    );
  };

  const renderCalendarView = () => {
    const monthStart = startOfMonth(currentDate);
    const monthEnd = endOfMonth(currentDate);
    const startDate = startOfWeek(monthStart);
    const endDate = endOfWeek(monthEnd);
    const calendarDays = eachDayOfInterval({ start: startDate, end: endDate });

    const nextMonth = () => setCurrentDate(addMonths(currentDate, 1));
    const prevMonth = () => setCurrentDate(subMonths(currentDate, 1));

    const remindersByDay = (day: Date) => remindersDayMap[format(day, 'yyyy-MM-dd')] || [];
    
    const selectedDateKey = format(selectedDate, 'yyyy-MM-dd');
    const selectedReminders = [...(remindersDayMap[selectedDateKey] || [])];
    
    selectedReminders.sort((a,b) => new Date(a.remindAt).getTime() - new Date(b.remindAt).getTime());

    const morningReminders = selectedReminders.filter(r => getHours(parseISO(r.remindAt)) < 12);
    const afternoonReminders = selectedReminders.filter(r => { const h = getHours(parseISO(r.remindAt)); return h >= 12 && h < 17; });
    const eveningReminders = selectedReminders.filter(r => { const h = getHours(parseISO(r.remindAt)); return h >= 17; });

    return (
      <div className="flex flex-col lg:flex-row h-full min-h-0 gap-4 overflow-y-auto lg:overflow-hidden pb-20 lg:pb-0">
        {/* Calendar Grid */}
        <div className="flex-1 flex flex-col bg-card border border-border rounded-xl overflow-hidden shadow-sm min-h-[500px] lg:min-h-0">
          {/* Header */}
          <div className="flex items-center justify-between p-4 border-b border-border bg-muted/10">
            <h2 className="text-lg font-bold text-foreground">{format(currentDate, 'MMMM yyyy')}</h2>
            <div className="flex items-center gap-1.5 bg-background border border-border rounded-lg p-0.5 shadow-sm">
              <button onClick={prevMonth} className="px-2 py-1.5 rounded-md hover:bg-muted text-muted-foreground transition-colors"><ChevronLeft className="w-4 h-4" /></button>
              <button onClick={() => setCurrentDate(new Date())} className="px-3 py-1 text-xs font-bold rounded-md hover:bg-muted text-foreground transition-colors">Today</button>
              <button onClick={nextMonth} className="px-2 py-1.5 rounded-md hover:bg-muted text-muted-foreground transition-colors"><ChevronRight className="w-4 h-4" /></button>
            </div>
          </div>
          {/* Weekdays */}
          <div className="grid grid-cols-7 border-b border-border bg-muted/20">
            {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(day => (
              <div key={day} className="py-2.5 text-center text-[10px] lg:text-[11px] font-bold text-muted-foreground uppercase tracking-widest">
                <span className="hidden sm:inline">{day}</span>
                <span className="sm:hidden">{day[0]}</span>
              </div>
            ))}
          </div>
          {/* Days */}
          <div className="flex-1 min-h-0 overflow-y-auto">
            <div className="grid grid-cols-7 auto-rows-[minmax(80px,1fr)] h-full">
              {calendarDays.map((day, idx) => {
                const dayReminders = remindersByDay(day);
                const isSelected = isSameDay(day, selectedDate);
                const isCurrentMonth = isSameMonth(day, monthStart);
                return (
                  <div key={day.toString()} onClick={() => setSelectedDate(day)}
                    className={`p-2 border-b border-border/60 cursor-pointer transition-all hover:bg-muted/40 flex flex-col gap-1.5 ${!isCurrentMonth ? 'opacity-40 bg-muted/5' : ''} ${isSelected ? 'bg-indigo-50/50 dark:bg-indigo-900/10 shadow-[inset_0_0_0_1px_rgba(139,92,246,0.5)] z-10' : ''} ${idx % 7 !== 6 ? 'border-r' : ''}`}>
                    <div className="flex items-center justify-between">
                      <span className={`text-xs font-semibold w-6 h-6 flex items-center justify-center rounded-full ${isToday(day) ? 'bg-indigo-600 text-white shadow-sm' : isSelected ? 'bg-indigo-200 text-indigo-900 dark:bg-indigo-800 dark:text-indigo-100' : 'text-foreground'}`}>
                        {format(day, 'd')}
                      </span>
                    </div>
                    <div className="flex-1 overflow-y-auto space-y-1 mt-0.5 pr-1 no-scrollbar">
                      {dayReminders.slice(0, 3).map(r => (
                        <div key={r.id} className={`text-[10px] font-medium px-1.5 py-1 rounded truncate flex items-center gap-1 border border-transparent ${r.isActive ? 'bg-indigo-100/60 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-300 hover:border-indigo-200' : 'bg-muted/50 text-muted-foreground'}`}>
                          <div className={`w-1 h-1 rounded-full flex-shrink-0 ${r.isActive ? 'bg-indigo-500' : 'bg-muted-foreground'}`} />
                          <span className="truncate">{format(parseISO(r.remindAt), 'h:mma')} - {r.title}</span>
                        </div>
                      ))}
                      {dayReminders.length > 3 && (
                        <div className="text-[10px] font-bold text-muted-foreground pl-1 mt-1">
                          + {dayReminders.length - 3} more
                        </div>
                      )}
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        </div>

        {/* Sidebar */}
        <div className="w-full lg:w-[300px] flex flex-col bg-card border border-border rounded-xl overflow-hidden shadow-sm flex-shrink-0">
          <div className="p-4 border-b border-border flex flex-col gap-1 bg-muted/10">
            <h3 className="font-bold text-base text-foreground">{format(selectedDate, 'EEEE, MMMM d')}</h3>
            <div className="text-xs font-medium text-muted-foreground flex items-center justify-between">
              <span>{selectedReminders.length} reminder{selectedReminders.length !== 1 ? 's' : ''}</span>
              <button onClick={() => setViewMode('list')} className="hover:text-foreground underline decoration-muted-foreground/30 underline-offset-2">View List</button>
            </div>
          </div>
          <div className="flex-1 overflow-y-auto p-4 space-y-6">
            <TimeBlock title="Morning" reminders={morningReminders} />
            <TimeBlock title="Afternoon" reminders={afternoonReminders} />
            <TimeBlock title="Evening" reminders={eveningReminders} />
            {selectedReminders.length === 0 && (
              <div className="text-center py-12 flex flex-col items-center">
                <div className="w-12 h-12 rounded-full bg-muted/50 flex items-center justify-center mb-3 text-muted-foreground">
                  <Calendar className="w-5 h-5" />
                </div>
                <p className="text-sm font-semibold text-foreground">No Reminders</p>
                <p className="text-xs text-muted-foreground mt-1 max-w-[200px] mx-auto">You're all clear for this day.</p>
              </div>
            )}
          </div>
        </div>
      </div>
    );
  };

  /* ─── Render ─────────────────────────────────────────────────────────── */
  return (
    <div className="h-full flex flex-col min-h-0 bg-slate-50 dark:bg-slate-950 overflow-hidden">
      <div className="flex-1 flex flex-col h-full animate-in fade-in duration-300">
        
        {/* Unified Controls Toolbar */}
        <div className="px-6 py-4 bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-700 flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest mr-1 hidden sm:inline">Status:</span>
            {(['all','active','inactive'] as const).map(f => (
              <Button 
                key={f} 
                variant={filterStatus === f ? 'secondary' : 'outline'} 
                size="sm"
                onClick={() => setFilterStatus(f)}
                className={`h-8 px-4 rounded-full font-bold text-[10px] uppercase tracking-tight transition-all active:scale-95 ${filterStatus === f ? 'bg-indigo-50 border-indigo-200 text-indigo-700 shadow-sm' : 'text-slate-500 border-slate-200 hover:bg-slate-50'}`}
              >
                {f}
              </Button>
            ))}
          </div>

          <div className="flex items-center gap-3 w-full lg:w-auto">
            <div className="relative flex-1 lg:w-72">
              <Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" />
              <Input 
                placeholder="Search reminders..." 
                className="pl-10 h-9 text-xs border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 hover:bg-white dark:hover:bg-slate-700 focus:bg-white dark:focus:bg-slate-700 text-slate-900 dark:text-slate-100 transition-all shadow-sm rounded-lg w-full" 
                value={search} 
                onChange={e => setSearch(e.target.value)} 
              />
              {search && (
                <button 
                  onClick={() => setSearch('')}
                  className="absolute right-3 top-2.5 p-0.5 rounded-full hover:bg-slate-200 transition-colors"
                >
                  <X className="h-3 w-3 text-slate-500" />
                </button>
              )}
            </div>

            {/* Clear system-generated reminders */}
            <Button
              size="sm"
              variant="outline"
              onClick={handlePurgeSystemReminders}
              disabled={purging}
              title="Delete all auto-generated reminders (task updates, mentions)"
              className="h-9 px-3 gap-1.5 text-[10px] font-bold uppercase tracking-tight border-red-200 text-red-600 hover:bg-red-50 hover:border-red-300 active:scale-95 transition-all whitespace-nowrap flex-shrink-0"
            >
              <ShieldAlert className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">{purging ? 'Clearing…' : 'Clear System'}</span>
            </Button>
          </div>
        </div>

        {/* ── Main content ── */}
      {viewMode === 'list' ? (
        <div className="flex-1 min-h-0 overflow-y-auto px-6 pb-6">
        {filtered.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-24 text-center">
            <div className="w-16 h-16 rounded-2xl bg-indigo-50 dark:bg-indigo-900/20 flex items-center justify-center mb-4">
              <BellOff className="w-7 h-7 text-indigo-400" />
            </div>
            <p className="text-sm font-semibold text-foreground">No reminders found</p>
            <p className="text-xs text-muted-foreground mt-1">
              {search ? 'Try a different search term.' : 'Hit "New Reminder" to create your first one.'}
            </p>
            {!search && (
              <button onClick={openCreate} className="mt-4 flex items-center gap-2 px-4 py-2 rounded-full bg-indigo-600 text-white text-sm font-semibold hover:bg-indigo-700 transition-colors">
                <Plus className="w-4 h-4" /> Create Reminder
              </button>
            )}
          </div>
        ) : (
          <div className="space-y-2.5 max-w-4xl">
            {filtered.map(rem => {
              const rel         = getRelativeTime(rem.remindAt);
              const isOwner     = rem.createdBy === currentUser?.id;
              const isAdmin     = (currentUser as any)?.privileges?.users?.canManage || (currentUser as any)?.role === 'admin' || (currentUser as any)?.role === 'co-admin';
              const canEdit     = isOwner || isAdmin;
              const linkedTask  = rem.mainTaskId ? mainTasks.find(t => t.id === rem.mainTaskId) : null;
              const creatorUser = users.find(u => u.id === rem.createdBy);
              const isSelected  = selected?.id === rem.id;

              return (
                <motion.div key={rem.id} id={`reminder-${rem.id}`}
                  initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.25 }}
                  className={`rounded-2xl border transition-all ${
                    !rem.isActive
                      ? 'bg-muted/20 border-border/40 opacity-60'
                      : rel.tone === 'overdue'
                        ? 'bg-red-50/50 dark:bg-red-950/20 border-red-200/60 dark:border-red-900/40'
                        : rel.tone === 'today'
                          ? 'bg-indigo-50/40 dark:bg-indigo-950/20 border-indigo-200/60 dark:border-indigo-900/30'
                          : 'bg-card border-border hover:border-indigo-200/60 hover:shadow-sm'
                  }`}>

                  {/* Card header row */}
                  <div className="flex items-start gap-3 p-4">

                    {/* Status dot */}
                    <div className={`mt-0.5 w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0 ${
                      rel.tone === 'overdue' ? 'bg-red-100 dark:bg-red-900/30' :
                      rem.isActive ? 'bg-indigo-100 dark:bg-indigo-900/20' : 'bg-muted'
                    }`}>
                      {rel.tone === 'overdue'
                        ? <AlertCircle className="w-4.5 h-4.5 text-red-500" />
                        : rem.isActive
                          ? <Bell className="w-4.5 h-4.5 text-indigo-500" />
                          : <BellOff className="w-4.5 h-4.5 text-muted-foreground" />
                      }
                    </div>

                    {/* Content */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between gap-2">
                        <div className="min-w-0">
                          <h3 className="text-sm font-semibold text-foreground truncate">{rem.title}</h3>
                          {rem.body && (
                            <p className={`text-xs text-muted-foreground mt-0.5 ${isSelected ? '' : 'line-clamp-1'}`}>{rem.body}</p>
                          )}
                        </div>

                        {/* Actions */}
                        <div className="flex items-center gap-0.5 flex-shrink-0 ml-2">
                          <button onClick={() => setSelected(isSelected ? null : rem)}
                            title="View details"
                            className={`p-1.5 rounded-lg transition-colors ${isSelected ? 'bg-indigo-100 text-indigo-600' : 'text-muted-foreground hover:bg-muted'}`}>
                            <Eye className="w-3.5 h-3.5" />
                          </button>
                          {canEdit && (
                            <>
                              <button onClick={() => toggleReminderActive(rem.id)}
                                title={rem.isActive ? 'Pause' : 'Resume'}
                                className={`p-1.5 rounded-lg transition-colors ${rem.isActive ? 'text-indigo-500 hover:bg-indigo-50' : 'text-muted-foreground hover:bg-muted'}`}>
                                {rem.isActive ? <ToggleRight className="w-3.5 h-3.5" /> : <ToggleLeft className="w-3.5 h-3.5" />}
                              </button>
                              <button onClick={() => openEdit(rem)} title={isAdmin && !isOwner ? 'Edit (Admin Override)' : 'Edit'}
                                className="p-1.5 rounded-lg text-muted-foreground hover:bg-muted transition-colors">
                                <Edit3 className="w-3.5 h-3.5" />
                              </button>
                              <button onClick={() => deleteReminder(rem.id)} title={isAdmin && !isOwner ? 'Delete (Admin Override)' : 'Delete'}
                                className="p-1.5 rounded-lg text-muted-foreground hover:bg-red-50 hover:text-red-500 transition-colors">
                                <Trash2 className="w-3.5 h-3.5" />
                              </button>
                            </>
                          )}
                        </div>
                      </div>

                      {/* Meta row */}
                      <div className="flex flex-wrap items-center gap-x-3 gap-y-1.5 mt-2">
                        {/* Time */}
                        <span className={`flex items-center gap-1 text-xs ${toneStyles[rel.tone]}`}>
                          <Clock className={`w-3 h-3 ${toneIconStyles[rel.tone]}`} />
                          {rel.label}
                        </span>

                        {/* Freq badge */}
                        <span className={`inline-flex items-center gap-1 text-[10px] font-semibold px-2 py-0.5 rounded-full border ${FREQ_COLORS[rem.frequency as ReminderFrequency]}`}>
                          <RefreshCw className="w-2.5 h-2.5" />{FREQ_LABELS[rem.frequency as ReminderFrequency]}
                        </span>

                        {/* Email badge */}
                        {rem.sendEmail && (
                          <span className="inline-flex items-center gap-1 text-[10px] font-semibold px-2 py-0.5 rounded-full bg-blue-50 text-blue-600 border border-blue-200">
                            <Mail className="w-2.5 h-2.5" /> Email
                          </span>
                        )}

                        {/* Linked task */}
                        {linkedTask && (
                          <span className="inline-flex items-center gap-1 text-[10px] font-semibold px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200 max-w-[140px]">
                            <Link2 className="w-2.5 h-2.5 flex-shrink-0" />
                            <span className="truncate">{linkedTask.title}</span>
                          </span>
                        )}

                        {/* Recipient avatars */}
                        {rem.recipientIds.length > 0 && (
                          <div className="flex items-center -space-x-1 ml-auto">
                            {rem.recipientIds.slice(0, 5).map((id: string) => {
                              const u = users.find(u => u.id === id);
                              if (!u) return null;
                              return (
                                <div key={id} title={u.name}
                                  className={`w-5 h-5 rounded-full border-2 border-card text-[8px] font-bold text-white flex items-center justify-center ${u.avatarColor}`}>
                                  {u.name.split(' ').map((n: string) => n[0]).join('').slice(0, 2)}
                                </div>
                              );
                            })}
                            {rem.recipientIds.length > 5 && (
                              <div className="w-5 h-5 rounded-full border-2 border-card bg-muted text-[8px] font-bold text-muted-foreground flex items-center justify-center">
                                +{rem.recipientIds.length - 5}
                              </div>
                            )}
                          </div>
                        )}

                        {/* Creator badge */}
                        {isOwner ? (
                          <span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full bg-indigo-100 text-indigo-700 border border-indigo-200 ml-auto">
                            ✦ Created by You
                          </span>
                        ) : (
                          <span className="inline-flex items-center gap-1 text-[10px] font-medium px-2 py-0.5 rounded-full bg-slate-100 text-slate-500 border border-slate-200 ml-auto">
                            👤 {creatorUser?.name?.split(' ')[0] ?? 'System'}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>

                  {/* Expanded detail panel */}
                  <AnimatePresence>
                    {isSelected && (
                      <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.2 }}
                        className="overflow-hidden border-t border-border/50">
                        <div className="p-4 pt-3.5 grid grid-cols-2 sm:grid-cols-4 gap-4 bg-muted/20">
                          <div>
                            <p className="text-[10px] font-bold uppercase tracking-wide text-muted-foreground mb-1">Created by</p>
                            <p className="text-xs font-medium text-foreground">{creatorUser?.name ?? '—'}</p>
                          </div>
                          <div>
                            <p className="text-[10px] font-bold uppercase tracking-wide text-muted-foreground mb-1">End At</p>
                            <p className="text-xs font-medium text-foreground">
                              {rem.endAt ? format(parseISO(rem.endAt), 'MMM d, yyyy') : 'No end date'}
                            </p>
                          </div>
                          <div>
                            <p className="text-[10px] font-bold uppercase tracking-wide text-muted-foreground mb-1">Status</p>
                            <span className={`inline-flex items-center gap-1 text-[10px] font-semibold px-2 py-0.5 rounded-full border ${rem.isActive ? 'bg-green-50 text-green-700 border-green-200' : 'bg-muted text-muted-foreground border-border'}`}>
                              {rem.isActive ? 'Active' : 'Paused'}
                            </span>
                          </div>
                          <div>
                            <p className="text-[10px] font-bold uppercase tracking-wide text-muted-foreground mb-1">Recipients</p>
                            <p className="text-xs font-medium text-foreground">
                              {rem.recipientIds.map((id: string) => users.find(u => u.id === id)?.name?.split(' ')[0]).filter(Boolean).join(', ') || '—'}
                            </p>
                          </div>
                          {canEdit && (
                            <div className="col-span-2 sm:col-span-4 flex gap-2 pt-1 border-t border-border/40">
                              <button onClick={() => openEdit(rem)}
                                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-indigo-600 hover:bg-indigo-700 text-white transition-colors">
                                <Edit3 className="w-3 h-3" /> Edit Reminder
                              </button>
                            </div>
                          )}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>
              );
            })}
          </div>
        )}
        </div>
      ) : (
        <div className="flex-1 min-h-0 px-6 pb-5 pt-2">
          {renderCalendarView()}
        </div>
      )}

      {/* ── Modal ── */}
      <AnimatePresence>
        {showForm && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm"
            onClick={e => { if (e.target === e.currentTarget) setShowForm(false); }}>
            <motion.div initial={{ opacity: 0, scale: 0.95, y: 20 }} animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }} transition={{ duration: 0.2, ease: [0.25, 0.46, 0.45, 0.94] }}
              className="w-full max-w-lg bg-card border border-border rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">

              {/* Modal header */}
              <div className="flex items-center gap-3 px-6 py-4 border-b border-border flex-shrink-0">
                <div className="w-9 h-9 rounded-xl bg-indigo-100 dark:bg-indigo-900/30 flex items-center justify-center">
                  <Bell className="w-4 h-4 text-indigo-600" />
                </div>
                <div className="flex-1">
                  <h3 className="text-base font-semibold text-foreground">{editingId ? 'Edit Reminder' : 'New Reminder'}</h3>
                  <p className="text-[11px] text-muted-foreground">Set a timed notification for your team</p>
                </div>
                <button onClick={() => setShowForm(false)}
                  className="w-8 h-8 rounded-full hover:bg-muted flex items-center justify-center text-muted-foreground transition-colors">
                  <X className="w-4 h-4" />
                </button>
              </div>

              <form onSubmit={handleSubmit} className="overflow-y-auto flex-1 px-6 py-5 space-y-4">
                {/* Title */}
                <div>
                  <label className="block text-xs font-semibold text-foreground mb-1.5">Title *</label>
                  <input value={form.title} onChange={e => setForm(p => ({ ...p, title: e.target.value }))}
                    placeholder="e.g. Submit weekly report"
                    className="w-full px-3.5 py-2.5 rounded-xl border border-input bg-background text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring transition" />
                </div>

                {/* Message */}
                <div>
                  <label className="block text-xs font-semibold text-foreground mb-1.5">Message (optional)</label>
                  <textarea value={form.body} onChange={e => setForm(p => ({ ...p, body: e.target.value }))}
                    placeholder="Add any details or notes…" rows={2}
                    className="w-full px-3.5 py-2.5 rounded-xl border border-input bg-background text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring transition resize-none" />
                </div>

                {/* Dates */}
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-semibold text-foreground mb-1.5 flex items-center gap-1"><Calendar className="w-3 h-3" /> Start *</label>
                    <input type="datetime-local" value={form.remindAt} onChange={e => setForm(p => ({ ...p, remindAt: e.target.value }))}
                      className="w-full px-3.5 py-2.5 rounded-xl border border-input bg-background text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring transition" />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-foreground mb-1.5">End (optional)</label>
                    <input type="datetime-local" value={form.endAt} min={form.remindAt}
                      onChange={e => setForm(p => ({ ...p, endAt: e.target.value }))}
                      className="w-full px-3.5 py-2.5 rounded-xl border border-input bg-background text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring transition" />
                  </div>
                </div>

                {/* Frequency */}
                <div>
                  <label className="block text-xs font-semibold text-foreground mb-2 flex items-center gap-1"><RefreshCw className="w-3 h-3" /> Repeat</label>
                  <div className="grid grid-cols-3 gap-2">
                    {(['once','hourly','every_6_hours','daily','weekly','monthly'] as ReminderFrequency[]).map(f => (
                      <button key={f} type="button" onClick={() => setForm(p => ({ ...p, frequency: f }))}
                        className={`py-2 rounded-xl text-xs font-semibold border-2 transition-all ${form.frequency === f ? 'border-indigo-500 bg-indigo-50 text-indigo-700 dark:bg-indigo-900/20' : 'border-border text-muted-foreground hover:border-indigo-300 hover:text-foreground'}`}>
                        {FREQ_LABELS[f]}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Recipients */}
                <div>
                  <label className="block text-xs font-semibold text-foreground mb-1.5 flex items-center gap-1"><Users className="w-3 h-3" /> Recipients *</label>
                  <button type="button" onClick={() => setRecipientOpen(p => !p)}
                    className="w-full flex items-center justify-between px-3.5 py-2.5 rounded-xl border border-border bg-background text-sm hover:bg-muted/40 transition">
                    <span className="text-muted-foreground text-xs">
                      {form.recipientIds.length === 0 ? 'Select recipients…' : `${form.recipientIds.length} selected`}
                    </span>
                    <ChevronDown className={`w-4 h-4 text-muted-foreground transition-transform ${recipientOpen ? 'rotate-180' : ''}`} />
                  </button>
                  <AnimatePresence>
                    {recipientOpen && (
                      <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }} className="overflow-hidden">
                        <div className="mt-1 rounded-xl border border-border bg-card overflow-y-auto max-h-36">
                          {activeUsers.map(u => {
                            const sel = form.recipientIds.includes(u.id);
                            return (
                              <button key={u.id} type="button" onClick={() => toggleRecipient(u.id)}
                                className={`w-full flex items-center gap-3 px-4 py-2.5 text-sm hover:bg-muted transition-colors ${sel ? 'bg-indigo-50/50 dark:bg-indigo-900/10' : ''}`}>
                                <div className={`w-6 h-6 rounded-full ${u.avatarColor} flex items-center justify-center text-white text-[9px] font-bold flex-shrink-0`}>
                                  {u.name.split(' ').map((n: string) => n[0]).join('').slice(0, 2)}
                                </div>
                                <span className="flex-1 text-left font-medium text-foreground text-xs">{u.name}</span>
                                {sel && <Check className="w-3.5 h-3.5 text-indigo-600 flex-shrink-0" />}
                              </button>
                            );
                          })}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                  {form.recipientIds.length > 0 && (
                    <div className="flex flex-wrap gap-1.5 mt-2">
                      {form.recipientIds.map(id => {
                        const u = activeUsers.find(u => u.id === id);
                        if (!u) return null;
                        return (
                          <span key={id} className="flex items-center gap-1 px-2 py-0.5 bg-indigo-50 dark:bg-indigo-900/20 text-indigo-700 dark:text-indigo-300 rounded-full text-[11px] font-medium border border-indigo-200 dark:border-indigo-800">
                            {u.name.split(' ')[0]}
                            <button type="button" onClick={() => toggleRecipient(id)} className="hover:text-indigo-500"><X className="w-3 h-3" /></button>
                          </span>
                        );
                      })}
                    </div>
                  )}
                </div>

                {/* Link task */}
                <div>
                  <label className="block text-xs font-semibold text-foreground mb-1.5 flex items-center gap-1"><Link2 className="w-3 h-3" /> Link to Task (optional)</label>
                  <select value={form.mainTaskId} onChange={e => setForm(p => ({ ...p, mainTaskId: e.target.value }))}
                    className="w-full px-3.5 py-2.5 rounded-xl border border-input bg-background text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring cursor-pointer">
                    <option value="">— None —</option>
                    {mainTasks.map(t => <option key={t.id} value={t.id}>{t.title}</option>)}
                  </select>
                </div>

                {/* Email toggle */}
                <div className="flex items-center justify-between px-4 py-3 rounded-xl bg-muted/40 border border-border">
                  <div>
                    <p className="text-sm font-semibold text-foreground">Email Notification</p>
                    <p className="text-[11px] text-muted-foreground">Also send email when this fires</p>
                  </div>
                  <button type="button" onClick={() => setForm(p => ({ ...p, sendEmail: !p.sendEmail }))} className="flex-shrink-0">
                    {form.sendEmail ? <ToggleRight className="w-7 h-7 text-indigo-600" /> : <ToggleLeft className="w-7 h-7 text-muted-foreground" />}
                  </button>
                </div>

                {/* Error */}
                {formError && (
                  <div className="flex items-center gap-2 px-4 py-3 bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-800 rounded-xl text-sm text-red-600 dark:text-red-400">
                    <AlertCircle className="w-4 h-4 flex-shrink-0" />{formError}
                  </div>
                )}

                {/* Footer */}
                <div className="flex items-center justify-end gap-2 pt-1 pb-1">
                  <Button type="button" onClick={() => setShowForm(false)}
                    className="px-4 h-auto py-2.5 rounded-xl border border-border text-sm font-semibold text-foreground bg-transparent hover:bg-muted transition-colors">
                    Cancel
                  </Button>
                  <Button type="submit"
                    className="px-5 h-auto py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-semibold transition-colors shadow-sm flex items-center gap-2">
                    {editingId ? <><CheckCircle2 className="w-4 h-4" /> Save Changes</> : <><Plus className="w-4 h-4" /> Create</>}
                  </Button>
                </div>
              </form>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  </div>
  );
}
