// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qivyzfdxrzmzhvgjfaed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpdnl6ZmR4cnptemh2Z2pmYWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxNzg2OTUsImV4cCI6MjA4Nzc1NDY5NX0.waynPrjsPHm5XyoR-Q7c7XnW4C1VbsNyi3M0jrzmZgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});